sessions_trim:
  cron: "0 1 * * *" # clear old (older than 30 days) session data (cookies) from DB
  class: 'SessionsTrimJob'
  queue: 'sessions_trim'
  args:
    queue: 'sessions_trim'
sync_nvd_base:
  cron: "*/30 * * * *" # execute local NVD base synchronization at every 30 minutes
  class: 'SyncNvdBaseJob'
  queue: 'sync_nvd_base'
  args:
    queue: 'sync_nvd_base'
