---
:concurrency: 24
staging:
  :concurrency: 24
production:
  :concurrency: 24
:queues:
  - default
  - now_scan_1
  - now_scan_2
  - scheduled_scan_1
  - scheduled_scan_2
  - free_shodan_scan
:limits:
  default: 1
  now_scan_1: 2
  now_scan_2: 2
  scheduled_scan_1: 4
  scheduled_scan_2: 14
  free_shodan_scan: 1
