---
:concurrency: 15
staging:
  :concurrency: 15
production:
  :concurrency: 15
:queues:
  - default
  - now_scan
  - scheduled_scan
  - free_shodan_scan
:limits:
  default: 1
  now_scan: 5
  scheduled_scan: 8
  free_shodan_scan: 1
