---
:concurrency: 26
staging:
  :concurrency: 26
production:
  :concurrency: 26
:queues:
  - default
  - now_scan_1
  - now_scan_2
  - scheduled_scan_1
  - scheduled_scan_2
  - free_shodan_scan
  - reset_nvd_base
  - sync_nvd_base
:limits:
  default: 1
  now_scan_1: 2
  now_scan_2: 2
  scheduled_scan_1: 4
  scheduled_scan_2: 14
  free_shodan_scan: 1
  reset_nvd_base: 1
  sync_nvd_base: 1

