---
:concurrency: 12
staging:
  :concurrency: 12
production:
  :concurrency: 12
:queues:
  - default
  - now_scan
  - scheduled_scan
  - free_shodan_scan
:limits:
  default: 1
  now_scan: 5
  scheduled_scan: 5
  free_shodan_scan: 1
