---
:concurrency: 21
staging:
  :concurrency: 21
production:
  :concurrency: 21
:queues:
  - default
  - now_scan
  - scheduled_scan
  - free_shodan_scan
:limits:
  default: 1
  now_scan: 5
  scheduled_scan: 14
  free_shodan_scan: 1
